### ISSUE TITLE
Open target="_blank" window in other settings?

### ISSUE THREAD

**Issue by Creadecon** [cba85/electron-webview#20]
Hello, I really like your Electron App. Thanks for sharing!

I have a question about the target="_blank" window. 

I have included an external website in my Index.html, which partly contains links that open in a new window target="_blank". Now I have the problem that the app, as it is now, opens a window with the same settings as the main window. In my case now "fullscreen: true". 

Is there a possibility that I can make separate settings for the "_blank" pages? e.g. width: 800, height: 600 and a slightly transparent?

**Comment by cba85** [comment]
Hello,

Thank you for your nice comment, and sorry for the delay. I think it's not a problem due to my code, but [it's something that depends on Electron apparently](https://stackoverflow.com/questions/48914542/cant-open-electron-webview-links-with-target-blank). And apparently, yes, it's possible to use `target="_bank"` to create a custom window :)

I can't help you more, I never use `target="_blank"` attribute on links in my electron applications.
