### ISSUE TITLE
Error process execute .exe 

### ISSUE THREAD

**Issue by rsferreirawork** [cba85/electron-webview#33]
After running the step by step presented in the tutorial, I have this problem. Do you know how to guide me how I can solve it?
_There was no code change!_

![image](https://user-images.githubusercontent.com/53823404/112038532-bb732800-8b21-11eb-903a-a0ca61b70d7d.png)

**Comment by cba85** [comment]
By just reading your error message, it seems you haven't installed [@electron/remote](https://github.com/electron/remote) package this project uses now (since Electron 12) : https://github.com/cba85/electron-webview#electron-12-update

**Comment by cba85** [comment]
The problem seems from your side and not from the project itself.

https://user-images.githubusercontent.com/720547/112148100-be335300-8bdd-11eb-94c7-14b596c42924.mov

**Comment by rsferreirawork** [comment]
First of all, thanks for your attention. 
I don't think I could explain it properly.

My problem starts after the `npm run package-win` command, the `npm start` command works normally for me too.

**Comment by cba85** [comment]
Yes, my bad, I haven't correctly understand your problem.

You were right, there was a bug when creating a package. I've had the same problem when I've tried to create a mac package.
I've just fixed the issue (simply by moving `@electron/remote` in `dependencies` instead `devDependencies` in `package.json` file).

I can't test it on Windows because I only have a mac with me, but normally it would works for you too 😉
