### ISSUE TITLE
access to camera and mic for video call

### ISSUE THREAD

**Issue by jupitern** [cba85/electron-webview#34]
Hi,
Great package. Any idea on how to grant access to camera and mic to use video calls on a given url ?
The camera turns on but after a few seconds gives the error that camera and mic was not found.

**Comment by cba85** [comment]
Hello, and thank you!

I think you have to add code to make mic and camera working with Electron: https://www.electronjs.org/docs/api/system-preferences#systempreferencesaskformediaaccessmediatype-macos

This project is just a quick-start tutorial I maintain for 4 years. It was made because I had to wrap a simple website in an app for a client.

Sorry I can't help you more.
